// flow-typed signature: b2af25310871d0e35cad6f7a3d253440
// flow-typed version: <<STUB>>/html-webpack-pug-plugin_v^0.3.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'html-webpack-pug-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'html-webpack-pug-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'html-webpack-pug-plugin/index' {
  declare module.exports: $Exports<'html-webpack-pug-plugin'>;
}
declare module 'html-webpack-pug-plugin/index.js' {
  declare module.exports: $Exports<'html-webpack-pug-plugin'>;
}
